# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(1A1B1A)
$foreground = rgb(F7FCF7)
$color0 = rgb(404140)
$color1 = rgb(39403A)
$color2 = rgb(5C645D)
$color3 = rgb(7F8980)
$color4 = rgb(A2ADA3)
$color5 = rgb(C4D2C5)
$color6 = rgb(E7F6E8)
$color7 = rgb(EBF2EB)
$color8 = rgb(A4A9A5)
$color9 = rgb(39403A)
$color10 = rgb(5C645D)
$color11 = rgb(7F8980)
$color12 = rgb(A2ADA3)
$color13 = rgb(C4D2C5)
$color14 = rgb(E7F6E8)
$color15 = rgb(EBF2EB)
