[opener]
edit = [
    { run = '${EDITOR:-nvim} %s', block = true, desc = "Edit" },
]
vlc = [
    { run = 'vlc %s', desc = "Abrir con VLC" },
]
mpv = [
    { run = 'mpv %s', desc = "Abrir con MPV" },
]
xdg = [
    { run = 'xdg-open %s', desc = "Abrir con la app predeterminada" },
]

[open]
rules = [
    { name = "*.{txt,md,json,yaml,yml,toml,fish,nix,lua,py,sh,js,ts,go,rs,cpp,c,h,hpp}", use = ["edit"] },
    { mime = "text/*", use = ["edit"] },
    { mime = "video/*", use = ["vlc", "mpv", "xdg"] },
]
