# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-d9d0ee91-af9e-42f9-afe6-130de625fc43";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-d9d0ee91-af9e-42f9-afe6-130de625fc43".device = "/dev/disk/by-uuid/d9d0ee91-af9e-42f9-afe6-130de625fc43";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/FDD8-996E";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-e801fd46-c89a-4dab-97ab-72ecdf46c786"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
