# Configuración de keyd
# Instalación: install keyd && ctl enable --now keyd
# Config location: /etc/keyd
# Get keys: keyd monitor

# US - Left
# q w e r t y u i o p [ ] \
#  a s d F g h J k l ; '
#   z x c v b n m , . /

# Colemak - Left
# q w f p g j l u y ; [ ] \
#  a r s T d h N e i o '
#   z x c v b k m , . /

[ids]
*

#========================#
#         MAIN           #
#========================#
[main]

space = overload(navbar, space)
# space = layer(navbar)
tab = layer(num)
# meta = layer(num)

alt = layer(hyprland)
meta = layer(hyprland-reversed)
rightalt = layer(hyprland)

capslock = layer(symbols)

#========================#
#       NAVIGATION       #
#========================#
[navbar]
# Modificadores en la fila central (Home Row Mods)
a = oneshot(control)
s = oneshot(shift)
d = oneshot(alt)
f = rightalt

# Flechas estilo Vim
j = left
k = down
l = right
i = up

# Movimiento y edición
h = backspace
g = delete
; = enter
u = home
o = end

# Teclas especiales de acceso rápido
q = esc
w = tab
1 = C-S-tab
2 = C-tab

# Others
z = oneshot(meta)
# Tmux
x = C-a
# VsCode shortcuts
c = oneshot(code)
# Obsidian
v = oneshot(obsidian)
# m = oneshot(hyprland)

# Windows Launchers
# capslock = oneshot(hyprland)
capslock = oneshot(num)
alt = oneshot(launchers)

#========================#
#        NUMBERS         #
#========================#
[num]
# Right
q = f1
w = f2
e = f3
r = f4

a = f5
s = f6
d = f7
f = f8

z = f9
x = f10
c = f11
v = f12

# Left

t = -
y = +
u = 7
i = 8
o = 9
p = .

g = /
h = *
j = 4
k = 5
l = 6
; = 0


b = \
n = =
m = 1
, = 2
. = 3

#========================#
#        SYMBOLS         #
#========================#
[symbols]
# Left

q = _
w = -
e = (
r = )
t = =

a = /
s = \
d = [
f = ]
g = |

z = <
x = >
c = {
v = }
b = ~

# Right

y = @
u = !
i = ?
o = $
p = #
[ = &

h = *
j = .
k = P
l = ,
; = p

n = ^
m = +
, = %
. = `

#========================#
#       HYPRLAND         #
#========================#
[hyprland]
# Workspaces
q = A-1
w = A-2
e = A-3

a = A-4
s = A-5
d = A-6
f = A-7

z = A-8
x = A-9
c = A-0

# Moverse entre workspaces de Hyprland (estilo Vim)
j = A-j
k = A-k
l = A-l
i = A-i

esc = M-q
space = A-space
tab = A-e

# Navegación entre ventanas
o = A-tab
u = A-S-tab

# Navegacion entre groups
. = A-.
, = A-,
h = A-h
v = A-v
t = A-t

#========================#
#    HYPRLAND REVERSED   #
#========================#
[hyprland-reversed]
# Workspaces
u = A-1
i = A-2
o = A-3

j = A-4
k = A-5
l = A-6
; = A-7

m = A-8
, = A-9
. = A-0

# Moverse entre workspaces de Hyprland (estilo Vim)
a = A-j
s = A-k
d = A-l
f = A-i

esc = M-q
space = A-space
tab = A-e

# Navegación entre ventanas
q = A-S-tab
e = A-tab

# Navegacion entre groups
z = A-.
x = A-,
h = A-h
v = A-v
t = A-t

#========================#
#       LAUNCHERS        #
#========================#
[launchers]
# Browser
b = M-b
# Terminal
j = M-f
# Code
# k = M-c
# Obsidian
# l = M-;

#========================#
#       APPCONTROL       #
#========================#
[appcontrol]
a = oneshot(shift)
s = oneshot(control)
d = oneshot(alt)
# Tmux
j = C-x
# vscode
# k = oneshot(code)
k = C-space
# Obsidian
l = oneshot(obsidian)

# [tmux]
# u = macro(C-x C-u)
# o = macro(C-x C-l)

#========================#
#         CODE           #
#========================#
[code]
# Docks
q = A-q
w = A-w

# Focus file explorer
a = macro(C-space q)

# Togle panel
c = macro(C-space f)

# Terminal
j = macro(C-space z)
z = macro(C-c C-c)

# Close tab
x = macro(C-space C-q)

# Collapse
u = C-S-[
o = C-S-]

# Go to breadcrums
f = C-S-.

[obsidian]
# Open symbols
j = C-;
# Edit file
k = C-k
# Run Command
l = C-r
# Open file
; = C-e
# Collapse
u = C-S--
o = C-S-=
