[General]
abstouchmode=true
audiocfg=0
backgroundgamepad=false
bitrate=10000
capturesyskeys=1
connwarnings=true
defaultver=2
detectnetblocking=true
fps=30
framepacing=false
gameopts=true
gamepadmouse=true
hdr=false
height=720
hostaudio=true
keepawake=true
language=0
latestsupportedversion-v1=99.99.99.99
mdns=true
mouseacceleration=false
multicontroller=true
muteonfocusloss=false
packetsize=0
quitAppAfter=false
reversescroll=false
richpresence=true
showperfoverlay=false
swapfacebuttons=false
swapmousebuttons=false
uidisplaymode=0
unlockbitrate=false
videocfg=0
videodec=0
vsync=true
width=1280
windowmode=1
yuv444=false

[gcmapping]
size=0

[hosts]
1\apps\1\appcollector=false
1\apps\1\directlaunch=false
1\apps\1\hdr=true
1\apps\1\hidden=false
1\apps\1\id=881448767
1\apps\1\name=Desktop
1\apps\2\appcollector=false
1\apps\2\directlaunch=false
1\apps\2\hdr=true
1\apps\2\hidden=false
1\apps\2\id=303580669
1\apps\2\name=Low Res Desktop
1\apps\3\appcollector=false
1\apps\3\directlaunch=false
1\apps\3\hdr=true
1\apps\3\hidden=false
1\apps\3\id=1093255277
1\apps\3\name=Steam Big Picture
1\apps\size=3
1\customname=false
1\hostname=the-grid-server
1\ipv6address=
1\ipv6port=0
1\localaddress=100.83.43.43
1\localport=47989
1\mac=@ByteArray(\0)
1\manualaddress=the-grid-server
1\manualport=47989
1\nvidiasw=false
1\remoteaddress=
1\remoteport=0
1\srvcert=@ByteArray(-----BEGIN CERTIFICATE-----\nMIIC0jCCAbqgAwIBAgIUP9Evpd80firDhD6XccKp7nysqswwDQYJKoZIhvcNAQEL\nBQAwIzEhMB8GA1UEAwwYU3Vuc2hpbmUgR2FtZXN0cmVhbSBIb3N0MB4XDTI2MDcw\nOTIzMDcxMFoXDTQ2MDcwNDIzMDcxMFowIzEhMB8GA1UEAwwYU3Vuc2hpbmUgR2Ft\nZXN0cmVhbSBIb3N0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAz4TQ\nstSx0qh0AyypROy7DpuSu3Lfra29PzIZ0srBTFpHV7hbMLNkpbUe99CnpHWSlF81\nk08iQivph6JZVUYAFpFIdQGB89b1Pa/Gzp9osrKAEn9z9p0i8iFzApvJkYJAauOE\n66+8E4E632vfKeVkQ1BSy9kTNqp+0aYDAg54UsXA0AmPhevmXTnHk7DWyk4KguNO\nCbFkYK6691lNoSenJQCrcRriJChImDxQtsm19SGEChn2B/bDm4vvBJipVZnV47du\n/oUJtJcM3hC3+tWyn/Y99h/7sOLe1B7zW9b2oLMpRgsEKdUTtFadIhClpo8JJEyw\nmnWnwGKpP74aYkcxBQIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQAe93fVw1bP6Mpx\naFh9Vp/v9RSMAjevEmBy6LFRb1rrfjfmvckIn0WyKKrrgyKfb8Ahsi1hw87pzxn5\nMGaR8U2t6GO6FYQdaGfAX2I1hL3vaEzROjl/Q74t+VqxIZJ8niRBSUbt85yIr+xS\nhbBCgqZFcY5ijKK63OcEkfb1LybOQHwt1CPPpHGNZZmIvYyRMWk8ts8vbrobJ6ZK\nypUAEXqSIj7YFpkVlHj5KITiYJkREpDe2zG2oScBPSnq9kotzPCl+9GNrXQ0gw5B\n3hYFc/c1m8ZwmTZw1usP0YLZp3uAQ8rZ8Gjn57tZdbbh7kJK7chvDTnx6lYWB/GV\nXbOdT26G\n-----END CERTIFICATE-----\n)
1\uuid=F5D3D3ED-9AC7-B82E-879A-446DCC8EFAE0
size=1
