alias bruno="nix run nixpkgs#bruno"
alias remmina="nix run nixpkgs#remmina"
alias office="nix run nixpkgs#onlyoffice-desktopeditors"
alias zoom="nix run nixpkgs#zoom-us"
alias cad="nix run nixpkgs#qcad"
