return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	main = "nvim-treesitter.configs",
	opts = {
		ensure_installed = {
			"vim",
			"lua",
			"vimdoc",
			"javascript",
			"typescript",
			"html",
			"css",
			"go",
			"bash",
			"nix",
			"python",
			"java",
			"kotlin",
			"json",
			"yaml",
			"toml",
			"markdown",
			"markdown_inline",
			"latex",
			"sql",
		},
		sync_install = false,
		highlight = { enable = true },
		indent = { enable = true },
	},
}
