# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm_crypt" "ccp" "cryptd" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-94ba8d4d-69c2-4e02-bbcf-b3e026a2f520";
      fsType = "ext4";
      # Performance optimizations for DRAM-less SSD:
      # noatime/nodiratime: Disable access time updates to reduce write amplification
      # No 'discard': continuous TRIM means sync I/O on every delete. Batched
      # TRIM via fstrim.timer instead (services.fstrim.enable in default.nix).
      # Edit this list HERE. Never override it with lib.mkForce from another
      # module -- see the warning in default.nix.
      options = [ "noatime" "nodiratime" ];
    };

  boot.initrd.luks.devices."luks-94ba8d4d-69c2-4e02-bbcf-b3e026a2f520" = {
    device = "/dev/disk/by-uuid/94ba8d4d-69c2-4e02-bbcf-b3e026a2f520";
    # allowDiscards: Pass TRIM commands through the LUKS encryption layer
    allowDiscards = true;
    # bypassWorkqueues: Skip kcryptd workqueues to reduce I/O latency on SSDs
    bypassWorkqueues = true;
  };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F404-FC52";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = lib.mkForce [
    {
      device  = "/dev/disk/by-partuuid/4dd5ab30-e6ef-4e72-bcde-2f65714cd242";
      # randomEncryption: NixOS re-keys the LUKS header with a random key
      # at every boot. No passphrase prompt, no key material at rest,
      # forward secrecy for swap contents. See boot-lockout-postmortem.md
      # §10.1 Option 1.
      randomEncryption = {
        enable         = true;
        allowDiscards  = true;
      };
    }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
