# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm_crypt" "ccp" "cryptd" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-94ba8d4d-69c2-4e02-bbcf-b3e026a2f520";
      fsType = "ext4";
      # Performance optimizations for DRAM-less SSD:
      # noatime/nodiratime: Disable access time updates to reduce write amplification
      # discard: Enable continuous TRIM to inform the SSD about free blocks
      options = [ "noatime" "nodiratime" "discard" ];
    };

  boot.initrd.luks.devices."luks-94ba8d4d-69c2-4e02-bbcf-b3e026a2f520" = {
    device = "/dev/disk/by-uuid/94ba8d4d-69c2-4e02-bbcf-b3e026a2f520";
    # allowDiscards: Pass TRIM commands through the LUKS encryption layer
    allowDiscards = true;
    # bypassWorkqueues: Skip kcryptd workqueues to reduce I/O latency on SSDs
    bypassWorkqueues = true;
  };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F404-FC52";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-005a1c08-56f9-4c42-a517-d075adc11615"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
