# vim:set ft=tmux:
## name: The Grid (Neon Contrast)

# Main (Colores Neón)
set -ogq @thm_strong_primary "#00bfff"
set -ogq @thm_primary "#00ffff"
set -ogq @thm_light_primary "#e0ffff"
set -ogq @thm_secondary "#ff8c00"
set -ogq @thm_prefix "#ff003c"
set -ogq @thm_fg "#ffffff"

# Surfaces and overlays
set -ogq @thm_core "default"
set -ogq @thm_mantle "#000000"
set -ogq @thm_surface "#121212"
set -ogq @thm_visual "#00ffff"

# General
set -ogq @thm_red "#ff003c"
set -ogq @thm_orange "#ff8c00"
set -ogq @thm_yellow "#f1fa8c"
set -ogq @thm_green "#50fa7b"
set -ogq @thm_teal "#8be9fd"
set -ogq @thm_blue "#00bfff"
set -ogq @thm_indigo "#bd93f9"
